import type { MockEntityRecord } from "./mock-store";

export type Fixtures = {
  datasetVersion: number;
  entities: Record<string, MockEntityRecord[]>;
};

/**
 * Datos sintéticos, deterministas y revisables en PR. Sin Math.random(),
 * Date.now() ni new Date(). Usa contexto chileno (es-CL, RUT con K mayúscula,
 * teléfonos +56, fechas ISO, CLP entero, correos example.com).
 */
export const fixtures: Fixtures = {
  datasetVersion: 26,
  entities: {
    cliente: [
      {
        id: "cli-001",
        nombre: "Juan",
        correo: "juan.cardenas@example.com",
        rut: "16.482.937-5",
        servicioId: "srv-renegociacion",
        etapaActualId: "etp-reneg-03",
      },
      {
        id: "cli-002",
        nombre: "Javiera",
        correo: "javiera.rojas@example.com",
        rut: "15.204.336-8",
        servicioId: "srv-renegociacion",
        etapaActualId: "etp-reneg-02",
      },
      {
        id: "cli-003",
        nombre: "Ignacio",
        correo: "ignacio.bravo@example.com",
        rut: "12.345.678-5",
        servicioId: "srv-defensa-juicio",
        etapaActualId: "etp-lit-01",
      },
      {
        id: "cli-004",
        nombre: "Rosa",
        correo: "rosa.mella@example.com",
        rut: "9.876.543-3",
        servicioId: "srv-proteccion-patrimonial",
        etapaActualId: "etp-pp-02",
      },
      {
        id: "cli-005",
        nombre: "Marcela",
        correo: "marcela.ibanez@example.com",
        rut: "14.552.081-2",
        servicioId: "srv-defensa-juicio",
        etapaActualId: "etp-lit-00",
      },
      {
        id: "cli-006",
        nombre: "Patricio",
        correo: "patricio.vergara@example.com",
        rut: "11.203.764-9",
        servicioId: "srv-defensa-juicio",
        etapaActualId: "etp-lit-01",
      },
      {
        id: "cli-007",
        nombre: "Soledad",
        correo: "soledad.munoz@example.com",
        rut: "13.907.442-K",
        servicioId: "srv-liquidacion",
        etapaActualId: "etp-liq-03",
      },
      {
        id: "cli-008",
        nombre: "Héctor",
        correo: "hector.salas@example.com",
        rut: "8.442.315-6",
        servicioId: "srv-renegociacion",
        etapaActualId: "etp-reneg-05",
      },
      {
        id: "cli-013",
        nombre: "Rodrigo",
        correo: "rodrigo.paredes@example.com",
        rut: "14.099.562-8",
        servicioId: "srv-renegociacion",
        etapaActualId: "etp-reneg-05",
      },
      {
        id: "cli-012",
        nombre: "Valentina",
        correo: "valentina.cortes@example.com",
        rut: "15.842.073-K",
        servicioId: "srv-defensa-juicio",
        etapaActualId: "etp-lit-01",
      },
      {
        id: "cli-011",
        nombre: "Gonzalo",
        correo: "gonzalo.reyes@example.com",
        rut: "12.870.455-6",
        servicioId: "srv-defensa-juicio",
        etapaActualId: "etp-lit-01",
      },
      {
        id: "cli-010",
        nombre: "Andrea",
        correo: "andrea.lagos@example.com",
        rut: "17.664.209-1",
        servicioId: "srv-liquidacion",
        etapaActualId: "etp-liq-02",
      },
      {
        id: "cli-009",
        nombre: "Ximena",
        correo: "ximena.torres@example.com",
        rut: "10.338.771-4",
        servicioId: "srv-proteccion-patrimonial",
        etapaActualId: "etp-pp-01",
      },
    ],

    // Cada caja es un caso abierto en Streak. El inicio se arma con estas, no
    // con el servicio: por eso una misma persona puede ver el estado de su
    // renegociación y además la lista de sus juicios.
    caja: [
      // Juan: renegociación y nada más. La caja de monitoreo la tiene igual que
      // todos, y se ignora: no es un juicio, es la vigilancia por defecto.
      {
        id: "caj-001",
        clienteId: "cli-001",
        tipo: "renegociacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-reneg-03",
      },
      {
        id: "caj-010",
        clienteId: "cli-001",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Javiera: renegociación con un juicio y una escritura encima.
      {
        id: "caj-002",
        clienteId: "cli-002",
        tipo: "renegociacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-reneg-02",
      },
      {
        id: "caj-003",
        clienteId: "cli-002",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-4821-2026",
        acreedor: "Banco Estado",
        etapaId: "etp-lit-02",
      },
      {
        id: "caj-004",
        clienteId: "cli-002",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Declaración de bien familiar",
        etapaId: "etp-pp-02",
      },
      {
        id: "caj-024",
        clienteId: "cli-002",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-011",
        clienteId: "cli-002",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Ignacio: defensa en juicio con dos causas reales. La de monitoreo no
      // entra en la lista: no es un juicio suyo.
      {
        id: "caj-005",
        clienteId: "cli-003",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-1207-2026",
        acreedor: "Coopeuch",
        etapaId: "etp-lit-01",
      },
      {
        id: "caj-006",
        clienteId: "cli-003",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-3390-2025",
        acreedor: "Banco de Chile",
        etapaId: "etp-lit-02",
      },
      {
        id: "caj-031",
        clienteId: "cli-003",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-8842-2026",
        acreedor: "Banco BICE",
        etapaId: "etp-lit-04",
      },
      {
        id: "caj-007",
        clienteId: "cli-003",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Rosa: protección patrimonial con dos escrituras en marcha. Tiene caja en
      // juicio ejecutivo, pero es solo monitoreo: por eso su servicio principal
      // sigue siendo protección patrimonial.
      {
        id: "caj-008",
        clienteId: "cli-004",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Compraventa de inmueble",
        etapaId: "etp-pp-02",
      },
      {
        id: "caj-009",
        clienteId: "cli-004",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Constitución de sociedad",
        etapaId: "etp-pp-03",
      },
      // Su tercera escritura es del mismo tipo que la primera: en Streak no hay
      // con qué distinguirlas, y van en etapas distintas. Es un caso real, no un
      // dato repetido por error — se muestran las dos y lo que las diferencia es
      // en qué va cada una.
      {
        id: "caj-023",
        clienteId: "cli-004",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Compraventa de inmueble",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-025",
        clienteId: "cli-004",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-012",
        clienteId: "cli-004",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Marcela: solo monitoreo y nada más. Es la única situación en que la caja
      // de monitoreo cuenta: su servicio es la vigilancia, y el estado del caso
      // es lo que se lo cuenta.
      {
        id: "caj-013",
        clienteId: "cli-005",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Patricio: dos causas reales y una escritura. Servicio principal
      // compuesto — «defensa en juicio con protección patrimonial»— y los dos
      // bloques al mismo nivel, sin estado del caso.
      {
        id: "caj-014",
        clienteId: "cli-006",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-2044-2026",
        acreedor: "Banco Santander",
        etapaId: "etp-lit-01",
      },
      {
        id: "caj-015",
        clienteId: "cli-006",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-7719-2025",
        acreedor: "Caja Los Andes",
        etapaId: "etp-lit-02",
      },
      {
        id: "caj-016",
        clienteId: "cli-006",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Usufructo vitalicio",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-032",
        clienteId: "cli-006",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Declaración de bien familiar",
        etapaId: "etp-pp-02",
      },
      {
        id: "caj-026",
        clienteId: "cli-006",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-017",
        clienteId: "cli-006",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Soledad: liquidación con una causa real encima. El servicio principal
      // sigue siendo la liquidación —lo concursal manda— y el juicio se le suma
      // abajo: es la estrategia concursal-táctica. El monitoreo no cuenta.
      {
        id: "caj-018",
        clienteId: "cli-007",
        tipo: "liquidacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-liq-03",
      },
      {
        id: "caj-030",
        clienteId: "cli-007",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-5514-2026",
        acreedor: "Banco Falabella",
        etapaId: "etp-lit-01",
      },
      {
        id: "caj-019",
        clienteId: "cli-007",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Héctor: renegociación con una escritura encima y ninguna causa. La
      // escritura se suma abajo sin quitarle el estado de su caso.
      {
        id: "caj-020",
        clienteId: "cli-008",
        tipo: "renegociacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-reneg-05",
      },
      {
        id: "caj-021",
        clienteId: "cli-008",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Mandato general de administración",
        etapaId: "etp-pp-03",
      },
      {
        id: "caj-027",
        clienteId: "cli-008",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-022",
        clienteId: "cli-008",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Rodrigo: renegociación con un juicio encima y ninguna escritura. Lo
      // concursal manda y el juicio se suma abajo, sin quitarle el estado de su
      // caso: es la estrategia concursal-táctica en su forma más simple.
      {
        id: "caj-046",
        clienteId: "cli-013",
        tipo: "renegociacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-reneg-05",
      },
      {
        id: "caj-047",
        clienteId: "cli-013",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-4417-2026",
        acreedor: "Cencosud",
        etapaId: "etp-lit-01",
      },
      {
        id: "caj-048",
        clienteId: "cli-013",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Valentina: el servicio compuesto en su forma mínima, una causa y una
      // escritura. Sirve para ver los dos bloques cuando cada lista tiene un
      // solo ítem, que es cuando peor se justifica que sean listas.
      {
        id: "caj-042",
        clienteId: "cli-012",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-6621-2026",
        acreedor: "Banco Security",
        etapaId: "etp-lit-01",
      },
      {
        id: "caj-043",
        clienteId: "cli-012",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Mandato general de administración",
        etapaId: "etp-pp-02",
      },
      {
        id: "caj-044",
        clienteId: "cli-012",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-045",
        clienteId: "cli-012",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Gonzalo: el servicio compuesto con dos causas y una sola escritura.
      {
        id: "caj-037",
        clienteId: "cli-011",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-3318-2026",
        acreedor: "Banco Itaú",
        etapaId: "etp-lit-02",
      },
      {
        id: "caj-038",
        clienteId: "cli-011",
        tipo: "defensaEnJuicio",
        estado: "activa",
        identificador: "C-9042-2025",
        acreedor: "Ripley",
        etapaId: "etp-lit-04",
      },
      {
        id: "caj-039",
        clienteId: "cli-011",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Constitución de sociedad",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-040",
        clienteId: "cli-011",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-041",
        clienteId: "cli-011",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Andrea: liquidación con una escritura encima y ninguna causa. Lo
      // concursal manda y la escritura se le suma abajo, sin quitarle el estado
      // de su caso.
      {
        id: "caj-033",
        clienteId: "cli-010",
        tipo: "liquidacion",
        estado: "activa",
        identificador: "",
        etapaId: "etp-liq-02",
      },
      {
        id: "caj-034",
        clienteId: "cli-010",
        tipo: "proteccionPatrimonial",
        estado: "activa",
        identificador: "Declaración de bien familiar",
        etapaId: "etp-pp-03",
      },
      {
        id: "caj-035",
        clienteId: "cli-010",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-036",
        clienteId: "cli-010",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },

      // Ximena: contrató protección patrimonial y todavía no arranca ninguna
      // escritura. Solo tiene la caja madre, así que su bloque de escrituras
      // está —es su servicio— pero vacío, diciéndolo.
      {
        id: "caj-028",
        clienteId: "cli-009",
        tipo: "proteccionPatrimonial",
        estado: "madre",
        identificador: "",
        etapaId: "etp-pp-01",
      },
      {
        id: "caj-029",
        clienteId: "cli-009",
        tipo: "defensaEnJuicio",
        estado: "monitoreo",
        identificador: "",
        etapaId: "etp-lit-00",
      },
    ],

    servicio: [
      {
        id: "srv-renegociacion",
        tipo: "renegociacion",
        nombre: "Renegociación de deudas",
        resumen:
          "Buscamos un acuerdo con tus acreedores para que pagues tus deudas en cuotas que sí puedas cumplir.",
        queEs:
          "La renegociación es un procedimiento para acordar con tus acreedores nuevas condiciones de pago, acordes a tus ingresos, y salir del sobreendeudamiento.",
      },
      {
        id: "srv-liquidacion",
        tipo: "liquidacion",
        nombre: "Liquidación de deudas",
        resumen:
          "Cuando ya no es posible pagar, buscamos que un tribunal extinga tus deudas para que puedas partir de nuevo.",
        queEs:
          "La liquidación es un procedimiento ante un tribunal para cuando las deudas ya no se pueden pagar. Un liquidador ordena tus bienes, los reparte según la ley, y el saldo que queda impago se extingue.",
      },
      {
        id: "srv-defensa-juicio",
        tipo: "defensaEnJuicio",
        nombre: "Defensa en juicio",
        resumen: "Te representamos ante el tribunal en cada causa que tengas abierta.",
        queEs:
          "En una defensa en juicio llevamos tu caso ante el tribunal: preparamos los escritos, presentamos las pruebas y te representamos en cada audiencia. Si tienes más de una causa, cada una avanza por su cuenta.",
      },
      {
        id: "srv-proteccion-patrimonial",
        tipo: "proteccionPatrimonial",
        nombre: "Protección Patrimonial",
        resumen:
          "Ordenamos y resguardamos lo que tienes a tu nombre dentro de lo que permite la ley.",
        queEs:
          "En la protección patrimonial revisamos qué tienes a tu nombre y cómo ordenarlo para dejarlo resguardado dentro de lo que permite la ley. El trabajo se concreta en escrituras, y cada una avanza por su cuenta.",
      },
    ],

    resultadoServicio: [
      {
        id: "res-reneg-01",
        servicioId: "srv-renegociacion",
        orden: 1,
        titulo: "Cuotas más bajas",
        texto: "Reducir lo que paga mensualmente por sus deudas.",
        icono: "baja",
      },
      {
        id: "res-reneg-02",
        servicioId: "srv-renegociacion",
        orden: 2,
        titulo: "Sin intereses",
        texto: "Establecer nuevas cuotas sin intereses.",
        icono: "acuerdo",
      },
      {
        id: "res-reneg-03",
        servicioId: "srv-renegociacion",
        orden: 3,
        titulo: "Período de gracia",
        texto: "Conseguir un período de gracia de 3 meses.",
        icono: "reloj",
      },
      {
        id: "res-reneg-04",
        servicioId: "srv-renegociacion",
        orden: 4,
        titulo: "Salir de DICOM",
        texto: "Si el cliente se encuentra en DICOM, eliminarlo del registro.",
        icono: "borron",
      },

      {
        id: "res-liq-01",
        servicioId: "srv-liquidacion",
        orden: 1,
        titulo: "Deudas extinguidas",
        texto: "Extinguir las deudas que quedan impagas al terminar el procedimiento.",
        icono: "borron",
      },
      {
        id: "res-liq-02",
        servicioId: "srv-liquidacion",
        orden: 2,
        titulo: "Juicios detenidos",
        texto: "Frenar los juicios de cobranza y los embargos en tu contra.",
        icono: "escudo",
      },
      {
        id: "res-liq-03",
        servicioId: "srv-liquidacion",
        orden: 3,
        titulo: "Bienes que la ley protege",
        texto: "Saber desde el principio qué bienes protege la ley y no entran en la liquidación.",
        icono: "casa",
      },

      {
        id: "res-lit-01",
        servicioId: "srv-defensa-juicio",
        orden: 1,
        titulo: "Un abogado en cada audiencia",
        texto:
          "Llevar tu caso ante el tribunal con un abogado que te representa en cada audiencia.",
        icono: "balanza",
      },
      {
        id: "res-lit-02",
        servicioId: "srv-defensa-juicio",
        orden: 2,
        titulo: "Respuesta dentro de plazo",
        texto: "Responder una demanda en tu contra dentro de los plazos legales.",
        icono: "reloj",
      },
      {
        id: "res-lit-03",
        servicioId: "srv-defensa-juicio",
        orden: 3,
        titulo: "Tu juicio en palabras simples",
        texto: "Entender en qué va tu juicio sin tener que leer el expediente.",
        icono: "lupa",
      },
      {
        id: "res-lit-04",
        servicioId: "srv-proteccion-patrimonial",
        orden: 1,
        titulo: "Bienes expuestos y protegidos",
        texto: "Saber qué bienes tuyos están expuestos y cuáles protege la ley.",
        icono: "casa",
      },
      {
        id: "res-pp-02",
        servicioId: "srv-proteccion-patrimonial",
        orden: 2,
        titulo: "Tu patrimonio ordenado",
        texto:
          "Dejar por escrito quién es dueño de qué, para que no quede en discusión más adelante.",
        icono: "documento",
      },
      {
        id: "res-pp-03",
        servicioId: "srv-proteccion-patrimonial",
        orden: 3,
        titulo: "Tu casa resguardada",
        texto: "Revisar si tu vivienda puede acogerse a las protecciones que contempla la ley.",
        icono: "casa",
      },
    ],

    etapa: [
      {
        id: "etp-reneg-01",
        servicioId: "srv-renegociacion",
        orden: 1,
        visibleParaCliente: true,
        nombreParaCliente: "Revisamos tus antecedentes",
        mensajePrincipal: "Estamos revisando si tu caso cumple los requisitos para renegociar.",
        queHaceLexy: "Revisamos tus deudas una por una: con quién están y cuánto suman.",
        queNecesitamosDelCliente:
          "Nada por ahora. Si falta algún documento, tu ejecutiva te lo pide.",
        quePuedePasarDespues: "Si cumples los requisitos, preparamos tu solicitud.",
        plazoEsperado: "Entre 5 y 10 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-reneg-02",
        servicioId: "srv-renegociacion",
        orden: 2,
        visibleParaCliente: true,
        nombreParaCliente: "Esperando el atraso en tus deudas",
        mensajePrincipal:
          "Tus deudas todavía no cumplen el atraso que la ley exige para renegociar.",
        queHaceLexy: "Vigilamos tus deudas para avisarte apenas se pueda avanzar.",
        queNecesitamosDelCliente:
          "Deja de pagar las deudas que acordamos y desactiva sus pagos automáticos.",
        quePuedePasarDespues:
          "Cuando se cumpla el plazo, te pedimos los documentos para presentar.",
        plazoEsperado: "Depende de tus deudas. Te avisamos cuando toque revisar de nuevo.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-reneg-03",
        servicioId: "srv-renegociacion",
        orden: 3,
        visibleParaCliente: true,
        nombreParaCliente: "Reuniendo tus antecedentes",
        mensajePrincipal:
          "Estamos reuniendo los antecedentes necesarios para poder preparar y presentar tu solicitud ante la Superintendencia.",
        queHaceLexy:
          "Tu ejecutivo legal te solicitará la documentación necesaria y estará revisando los documentos que envíes y orientándote durante el proceso, entregándote apoyo e indicaciones cuando sea necesario.",
        queNecesitamosDelCliente:
          "Reúne y carga en el portal los documentos solicitados dentro del plazo indicado, recuerda preguntar si tienes dudas o necesitas apoyo.",
        quePuedePasarDespues:
          "Una vez que hayas reunido toda la documentación, deberás firmar un mandato para que podamos representarte. Luego, tu abogado preparará y presentará tu solicitud ante la Superintendencia.",
        plazoEsperado: "Recuerda que debes enviar la documentación dentro de 10 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-reneg-04",
        servicioId: "srv-renegociacion",
        orden: 4,
        visibleParaCliente: false,
        nombreParaCliente: "Revisión final antes de presentar",
        mensajePrincipal: "Revisamos tu solicitud antes de presentarla.",
        queHaceLexy: "Un abogado comprueba que esté todo completo.",
        queNecesitamosDelCliente: "Nada. Es una revisión interna nuestra.",
        quePuedePasarDespues: "Presentamos tu solicitud ante la Superintendencia.",
        plazoEsperado: "2 o 3 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-reneg-05",
        servicioId: "srv-renegociacion",
        orden: 5,
        visibleParaCliente: true,
        nombreParaCliente: "Tu solicitud está en la Superintendencia",
        mensajePrincipal: "Presentamos tu solicitud y la Superintendencia la está revisando.",
        queHaceLexy: "Seguimos la revisión y respondemos cualquier observación.",
        queNecesitamosDelCliente:
          "No tomes deudas nuevas ni le pagues a un acreedor antes que a otro.",
        quePuedePasarDespues: "Si la declaran admisible, tus acreedores no pueden cobrarte.",
        plazoEsperado: "Entre 5 y 10 días hábiles. Ese plazo lo maneja la Superintendencia.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-reneg-06",
        servicioId: "srv-renegociacion",
        orden: 6,
        visibleParaCliente: true,
        nombreParaCliente: "Audiencia para fijar cuánto debes",
        mensajePrincipal: "En esta audiencia queda establecido cuánto debes y a quién.",
        queHaceLexy: "Vamos por ti y objetamos lo que no corresponda.",
        queNecesitamosDelCliente:
          "Avísanos si un acreedor te informa un monto distinto al que revisamos.",
        quePuedePasarDespues: "Fijado el monto, se cita a la audiencia de renegociación.",
        plazoEsperado: "La fecha la fija la Superintendencia. Te la avisamos apenas la tengamos.",
        contactoPrincipal: "ambos",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-reneg-07",
        servicioId: "srv-renegociacion",
        orden: 7,
        visibleParaCliente: true,
        nombreParaCliente: "Audiencia de renegociación",
        mensajePrincipal: "Es la audiencia donde se discute el acuerdo con tus acreedores.",
        queHaceLexy: "Defendemos tu propuesta y negociamos una cuota posible con tus ingresos.",
        queNecesitamosDelCliente: "Que estés disponible ese día por si hay que consultarte algo.",
        quePuedePasarDespues: "Si aceptan, se firma el acuerdo y empiezas a pagar lo pactado.",
        plazoEsperado: "La fecha la fija la Superintendencia.",
        contactoPrincipal: "ambos",
        nivelUrgencia: "urgente",
      },

      {
        id: "etp-liq-01",
        servicioId: "srv-liquidacion",
        orden: 1,
        visibleParaCliente: true,
        nombreParaCliente: "Revisamos si la liquidación te conviene",
        mensajePrincipal: "Estamos confirmando si liquidar es el mejor camino para ti.",
        queHaceLexy:
          "Comparamos cuánto debes con lo que podrías pagar y con los bienes que tienes.",
        queNecesitamosDelCliente: "Nada por ahora. Si necesitamos otro documento, te lo pedimos.",
        quePuedePasarDespues: "Si liquidar es el camino, preparamos tu solicitud para el tribunal.",
        plazoEsperado: "Entre 5 y 10 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-liq-02",
        servicioId: "srv-liquidacion",
        orden: 2,
        visibleParaCliente: true,
        nombreParaCliente: "Preparamos tu solicitud",
        mensajePrincipal: "Estamos preparando la solicitud para el tribunal.",
        queHaceLexy: "Ordenamos el detalle de tus deudas y de tus bienes.",
        queNecesitamosDelCliente:
          "Tu certificado de deudas y los papeles de los bienes a tu nombre.",
        quePuedePasarDespues: "Con todo listo presentamos y el tribunal revisa tu solicitud.",
        plazoEsperado: "5 días hábiles desde que recibimos tus documentos.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-liq-03",
        servicioId: "srv-liquidacion",
        orden: 3,
        visibleParaCliente: true,
        nombreParaCliente: "Tu caso está en el tribunal",
        mensajePrincipal: "Tu solicitud está en el tribunal, esperando resolución.",
        queHaceLexy: "Seguimos el expediente y respondemos lo que el tribunal pida.",
        queNecesitamosDelCliente:
          "Nada por ahora. Si te llega una notificación, avísale a tu ejecutiva.",
        quePuedePasarDespues: "Si el tribunal acoge la solicitud, designa a un liquidador.",
        plazoEsperado: "Los plazos los fija el tribunal. Te avisamos cada avance.",
        contactoPrincipal: "abogado",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-liq-04",
        servicioId: "srv-liquidacion",
        orden: 4,
        visibleParaCliente: true,
        nombreParaCliente: "Ya hay un liquidador a cargo",
        mensajePrincipal: "El tribunal designó un liquidador para tu caso.",
        queHaceLexy: "Acompañamos el proceso y revisamos cada paso del liquidador.",
        queNecesitamosDelCliente: "Responder al liquidador cuando te pida información.",
        quePuedePasarDespues: "Al terminar, el saldo que quede impago se extingue.",
        plazoEsperado: "Depende de cuántos bienes y acreedores haya. Suele tomar meses.",
        contactoPrincipal: "abogado",
        nivelUrgencia: "atencion",
      },

      {
        id: "etp-lit-00",
        servicioId: "srv-defensa-juicio",
        orden: 1,
        visibleParaCliente: true,
        nombreParaCliente: "Vigilando si te demandan",
        mensajePrincipal: "Hoy no tienes ninguna demanda en tu contra.",
        queHaceLexy: "Revisamos los tribunales buscando juicios de cobranza a tu nombre.",
        queNecesitamosDelCliente:
          "Si te llega un papel del tribunal, mándale una foto a tu ejecutiva ese mismo día.",
        quePuedePasarDespues:
          "Si aparece una demanda, la vas a ver acá y un abogado toma la defensa.",
        plazoEsperado: "Es permanente, mientras tengas tu servicio activo.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-lit-01",
        servicioId: "srv-defensa-juicio",
        orden: 2,
        visibleParaCliente: true,
        nombreParaCliente: "Estudiamos tu caso",
        mensajePrincipal: "Estamos revisando tus antecedentes para definir la estrategia.",
        queHaceLexy: "Un abogado lee tus documentos y revisa los plazos que corren.",
        queNecesitamosDelCliente: "Mándale a tu ejecutiva cualquier contrato o mensaje del caso.",
        quePuedePasarDespues: "Con la estrategia lista, presentamos tu defensa ante el tribunal.",
        plazoEsperado: "Entre 10 y 15 días hábiles.",
        contactoPrincipal: "abogado",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-lit-02",
        servicioId: "srv-defensa-juicio",
        orden: 3,
        visibleParaCliente: true,
        nombreParaCliente: "Presentamos tu caso al tribunal",
        mensajePrincipal: "Ya presentamos tu escrito. Ahora los plazos los fija el tribunal.",
        queHaceLexy: "Revisamos el expediente y respondemos cada trámite dentro de plazo.",
        queNecesitamosDelCliente:
          "Si te notifican algo en tu domicilio, avísale a tu ejecutiva ese mismo día.",
        quePuedePasarDespues: "El tribunal notifica a la otra parte y fija la primera audiencia.",
        plazoEsperado: "Los fija el tribunal y varían mucho. No podemos comprometer una fecha.",
        contactoPrincipal: "abogado",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-lit-03",
        servicioId: "srv-defensa-juicio",
        orden: 4,
        visibleParaCliente: false,
        nombreParaCliente: "Esperando respuesta del tribunal",
        mensajePrincipal: "",
        queHaceLexy: "",
        queNecesitamosDelCliente: "",
        quePuedePasarDespues: "",
        plazoEsperado: "",
        contactoPrincipal: "abogado",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-lit-04",
        servicioId: "srv-defensa-juicio",
        orden: 5,
        visibleParaCliente: true,
        nombreParaCliente: "Falta que firmes un documento",
        mensajePrincipal: "Necesitamos tu firma para presentar el escrito dentro del plazo.",
        queHaceLexy:
          "El escrito ya está redactado y revisado. Solo falta tu firma para presentarlo.",
        queNecesitamosDelCliente:
          "Firmar el poder que te envió tu ejecutiva. Sin eso no podemos actuar por ti.",
        quePuedePasarDespues:
          "Con tu firma presentamos dentro de plazo y el juicio sigue su curso.",
        plazoEsperado: "El tribunal fijó una fecha límite. Tu ejecutiva te dice cuál es.",
        contactoPrincipal: "ambos",
        nivelUrgencia: "urgente",
      },
      {
        id: "etp-pp-01",
        servicioId: "srv-proteccion-patrimonial",
        orden: 1,
        visibleParaCliente: true,
        nombreParaCliente: "Estudiamos qué tienes a tu nombre",
        mensajePrincipal: "Estamos revisando qué bienes están a tu nombre.",
        queHaceLexy: "Pedimos los certificados de tus propiedades y vehículos.",
        queNecesitamosDelCliente: "Cuéntanos si tienes bienes que no aparezcan en los registros.",
        quePuedePasarDespues: "Con el catastro listo te explicamos qué se puede proteger.",
        plazoEsperado: "Entre 10 y 15 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "atencion",
      },
      {
        id: "etp-pp-02",
        servicioId: "srv-proteccion-patrimonial",
        orden: 2,
        visibleParaCliente: true,
        nombreParaCliente: "Redactando la escritura",
        mensajePrincipal: "Estamos escribiendo el documento que vas a firmar ante notario.",
        queHaceLexy: "Un abogado redacta el texto y revisa cada cláusula.",
        queNecesitamosDelCliente: "Nada por ahora. Te mandamos el borrador antes de firmar.",
        quePuedePasarDespues: "Si estás de acuerdo con el borrador, coordinamos la firma.",
        plazoEsperado: "Entre 5 y 8 días hábiles.",
        contactoPrincipal: "ejecutiva",
        nivelUrgencia: "tranquilidad",
      },
      {
        id: "etp-pp-03",
        servicioId: "srv-proteccion-patrimonial",
        orden: 3,
        visibleParaCliente: true,
        nombreParaCliente: "Esperando la firma ante notario",
        mensajePrincipal: "El documento está listo. Falta que lo firmes ante notario.",
        queHaceLexy: "Dejamos la escritura en la notaría y un abogado te acompaña.",
        queNecesitamosDelCliente:
          "Ir a firmar con tu cédula vigente. Tu ejecutiva te confirma el día.",
        quePuedePasarDespues:
          "Firmada la escritura, la inscribimos y el resguardo queda constituido.",
        plazoEsperado: "Depende de la hora que tengas para ir a la notaría.",
        contactoPrincipal: "ambos",
        nivelUrgencia: "urgente",
      },
    ],

    contacto: [
      {
        id: "con-001",
        clienteId: "cli-001",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-002",
        clienteId: "cli-001",
        nombre: "Matías Fuenzalida",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 5530 9174",
      },
      {
        id: "con-003",
        clienteId: "cli-002",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-004",
        clienteId: "cli-002",
        nombre: "Matías Fuenzalida",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 5530 9174",
      },
      // Ignacio tiene asignado solo a su abogado: con dos causas andando, quien
      // le contesta es él. El botón flotante le abre WhatsApp directo.
      {
        id: "con-006",
        clienteId: "cli-003",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      {
        id: "con-007",
        clienteId: "cli-004",
        nombre: "Daniela Soto",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 4418 2036",
      },
      {
        id: "con-008",
        clienteId: "cli-004",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      // Marcela tiene asignada solo a su ejecutiva: todavía no la demanda nadie,
      // así que no hay abogado a cargo de ninguna causa.
      {
        id: "con-009",
        clienteId: "cli-005",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-011",
        clienteId: "cli-006",
        nombre: "Daniela Soto",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 4418 2036",
      },
      {
        id: "con-012",
        clienteId: "cli-006",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      {
        id: "con-013",
        clienteId: "cli-007",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-014",
        clienteId: "cli-007",
        nombre: "Matías Fuenzalida",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 5530 9174",
      },
      {
        id: "con-015",
        clienteId: "cli-008",
        nombre: "Daniela Soto",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 4418 2036",
      },
      {
        id: "con-016",
        clienteId: "cli-008",
        nombre: "Matías Fuenzalida",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 5530 9174",
      },
      {
        id: "con-025",
        clienteId: "cli-013",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-026",
        clienteId: "cli-013",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      {
        id: "con-023",
        clienteId: "cli-012",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-024",
        clienteId: "cli-012",
        nombre: "Matías Fuenzalida",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 5530 9174",
      },
      {
        id: "con-021",
        clienteId: "cli-011",
        nombre: "Daniela Soto",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 4418 2036",
      },
      {
        id: "con-022",
        clienteId: "cli-011",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      {
        id: "con-019",
        clienteId: "cli-010",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-020",
        clienteId: "cli-010",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
      {
        id: "con-017",
        clienteId: "cli-009",
        nombre: "Camila Rivera",
        rol: "ejecutiva",
        telefonoWhatsapp: "+56 9 6721 4488",
      },
      {
        id: "con-018",
        clienteId: "cli-009",
        nombre: "Andrés Peña",
        rol: "abogado",
        telefonoWhatsapp: "+56 9 7302 6641",
      },
    ],

    cuota: [
      {
        id: "cuo-016",
        clienteId: "cli-001",
        numero: 16,
        fechaVencimiento: "2026-08-06",
        monto: 9450,
        estado: "pagada",
      },
      {
        id: "cuo-017",
        clienteId: "cli-001",
        numero: 17,
        fechaVencimiento: "2026-09-06",
        monto: 9450,
        estado: "pagada",
      },
      {
        id: "cuo-018",
        clienteId: "cli-001",
        numero: 18,
        fechaVencimiento: "2026-10-06",
        monto: 9450,
        estado: "pendiente",
      },
      {
        id: "cuo-019",
        clienteId: "cli-001",
        numero: 19,
        fechaVencimiento: "2026-11-06",
        monto: 9450,
        estado: "pendiente",
      },
      {
        id: "cuo-103",
        clienteId: "cli-002",
        numero: 3,
        fechaVencimiento: "2026-08-15",
        monto: 12900,
        estado: "pagada",
      },
      {
        id: "cuo-104",
        clienteId: "cli-002",
        numero: 4,
        fechaVencimiento: "2026-10-15",
        monto: 12900,
        estado: "pendiente",
      },
      {
        id: "cuo-101",
        clienteId: "cli-003",
        numero: 4,
        fechaVencimiento: "2026-09-22",
        monto: 74900,
        estado: "pendiente",
      },
      {
        id: "cuo-102",
        clienteId: "cli-004",
        numero: 2,
        fechaVencimiento: "2026-09-30",
        monto: 121000,
        estado: "pendiente",
      },
      {
        id: "cuo-105",
        clienteId: "cli-005",
        numero: 6,
        fechaVencimiento: "2026-09-18",
        monto: 19900,
        estado: "pendiente",
      },
      {
        id: "cuo-106",
        clienteId: "cli-006",
        numero: 3,
        fechaVencimiento: "2026-10-02",
        monto: 148000,
        estado: "pendiente",
      },
      {
        id: "cuo-107",
        clienteId: "cli-007",
        numero: 9,
        fechaVencimiento: "2026-09-25",
        monto: 63500,
        estado: "pendiente",
      },
      {
        id: "cuo-108",
        clienteId: "cli-008",
        numero: 2,
        fechaVencimiento: "2026-10-10",
        monto: 87400,
        estado: "pendiente",
      },
      {
        id: "cuo-113",
        clienteId: "cli-013",
        numero: 7,
        fechaVencimiento: "2026-10-18",
        monto: 46800,
        estado: "pendiente",
      },
      {
        id: "cuo-112",
        clienteId: "cli-012",
        numero: 1,
        fechaVencimiento: "2026-10-12",
        monto: 99500,
        estado: "pendiente",
      },
      {
        id: "cuo-111",
        clienteId: "cli-011",
        numero: 2,
        fechaVencimiento: "2026-10-08",
        monto: 132000,
        estado: "pendiente",
      },
      {
        id: "cuo-110",
        clienteId: "cli-010",
        numero: 5,
        fechaVencimiento: "2026-10-05",
        monto: 58900,
        estado: "pendiente",
      },
      {
        id: "cuo-109",
        clienteId: "cli-009",
        numero: 1,
        fechaVencimiento: "2026-09-28",
        monto: 96000,
        estado: "pendiente",
      },
    ],

    configuracionPortal: [
      {
        id: "cfg-001",
        correoSoporte: "soporte@defensoriadeudor.cl",
        urlFormularioReclamos: "https://defensoriasalud.typeform.com/reclamos-lexy",
        // El enlace corto de reseña que entrega Google desde la ficha del
        // negocio. Reemplaza a la URL de búsqueda larga que se usaba antes, que
        // traía parámetros de la sesión del navegador de quien la copió y abría
        // la ficha entera en vez del formulario.
        urlResenasGoogle: "https://g.page/r/CZfUgMb0w7hAEBM/review",
        urlPagoEnLinea:
          "https://market.apio.cl/defensoria-deudor/login?redirect=%2Fdefensoria-deudor%2Fuserpanel%2Fcharges",
        // La cuenta de recaudación real, que la entregó el diseñador. No es un
        // dato personal: es la cuenta a la que se le transfiere y está para
        // mostrarse. En producción igual tiene que venir del backend — si
        // Finanzas la cambia, nadie debería tener que tocar el código.
        titularCuenta: "Asesorías Jurídicas Moller y Abadie Limitada",
        banco: "Banco de Chile",
        numeroCuenta: "00-162-36534-09",
        rutTitular: "77.727.144-K",
      },
    ],
  },
};
